# Generated by Django 3.1.4 on 2020-12-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0002_auto_20201230_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onemodels',
            old_name='nameModel',
            new_name='nameMahath',
        ),
    ]
