# Generated by Django 3.1.4 on 2020-12-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0004_employee_themahatah'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='number_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onemodels',
            name='number_mahatah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themahatah',
            name='number_pumps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
