# Generated by Django 3.1.4 on 2021-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0005_auto_20201230_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_car', models.CharField(max_length=50)),
                ('type_car', models.CharField(choices=[('T', 'Toyota'), ('H', 'Honda'), ('M', 'Marcides')], max_length=1)),
                ('number_car', models.IntegerField()),
            ],
        ),
    ]
