# Generated by Django 3.1.4 on 2021-01-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0006_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='themahatah',
            name='cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModelsApp.car', verbose_name='cars'),
        ),
    ]
