# Generated by Django 3.1.4 on 2021-01-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0008_auto_20210101_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themahatah',
            options={'ordering': ['cars'], 'verbose_name_plural': 'oxen'},
        ),
    ]
