# Generated by Django 3.1.4 on 2021-01-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0009_auto_20210101_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='themahatah',
            name='detaTime',
            field=models.DateField(auto_now=True),
        ),
    ]
