# Generated by Django 3.1.4 on 2021-01-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0011_auto_20210101_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themahatah',
            options={},
        ),
        migrations.RemoveField(
            model_name='themahatah',
            name='cars',
        ),
        migrations.AddField(
            model_name='themahatah',
            name='cars',
            field=models.ManyToManyField(to='ModelsApp.Car'),
        ),
    ]
